name: Vote Update

on:
  repository_dispatch:
    types: [vote]

jobs:
  update-vote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Commit vote
        run: |
          OLD=$(cat vote.json)
          NEW=$(echo "$OLD" "${{ github.event.client_payload.data }}" | jq -s 'add')
          echo "$NEW" | jq . > vote.json

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add vote.json
          git diff --quiet && git diff --staged --quiet || git commit -m "vote +1"
          git push
